apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-operator
  labels:
    app.kubernetes.io/part-of: algo.run
    app: pipeline-operator
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pipeline-operator
  template:
    metadata:
      labels:
        name: pipeline-operator
    spec:
      serviceAccountName: pipeline-operator
      containers:
        - name: pipeline-operator
          # Replace this with the built image name
          image: algohub/pipeline-operator:546c293930c54c124d78c8efafe187382138cd08
          command:
          - pipeline-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pipeline-operator"
