apiVersion: apps/v1
kind: Deployment
metadata:
  name: algorun-pipeline-operator
  labels:
    system: algorun
    tier: backend
    app: pipeline-operator
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      name: algorun-pipeline-operator
  template:
    metadata:
      labels:
        name: algorun-pipeline-operator
    spec:
      serviceAccountName: algorun-pipeline-operator
      containers:
        - name: pipeline-operator
          # Replace this with the built image name
          image: algohub/pipeline-operator:8847fd498642d659809f9aa7a10995650809a474
          command:
          - pipeline-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "algorun-pipeline-operator"
